# Generated by Django 5.1 on 2024-08-24 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_customuser_game_evenings_this_month_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_registered',
            field=models.BooleanField(default=False),
        ),
    ]
