# Generated by Django 5.1 on 2024-08-24 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_participant'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='friends_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
