# Generated by Django 5.1 on 2024-08-24 18:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_ordertable'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name': 'Город', 'verbose_name_plural': 'Города'},
        ),
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name': 'Мероприятие', 'verbose_name_plural': 'Мероприятия'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.AlterModelOptions(
            name='ordertable',
            options={'verbose_name': 'Заказ таблички', 'verbose_name_plural': 'Заказы табличек'},
        ),
        migrations.AlterModelOptions(
            name='participant',
            options={'verbose_name': 'Участник', 'verbose_name_plural': 'Участники'},
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Аватар'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='main.city', verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='game_evenings_this_month',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество игровых вечеров в этом месяце'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='game_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Игровое имя'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='games_played',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество сыгранных игр'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='games_played_this_month',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество сыгранных игр в этом месяце'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_registered',
            field=models.BooleanField(default=False, verbose_name='Зарегистрирован'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='main_city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='main_users', to='main.city', verbose_name='Основной город'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='points_earned',
            field=models.PositiveIntegerField(default=0, verbose_name='Заработанные очки'),
        ),
        migrations.AlterField(
            model_name='event',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='main.city', verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='event',
            name='current_players',
            field=models.PositiveIntegerField(default=0, verbose_name='Текущее количество игроков'),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(upload_to='events/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='event',
            name='max_players',
            field=models.PositiveIntegerField(verbose_name='Максимальное количество игроков'),
        ),
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='order',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.CharField(max_length=255, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='order',
            name='event_type',
            field=models.CharField(max_length=255, verbose_name='Тип мероприятия'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='ordertable',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='ordertable',
            name='game_name',
            field=models.CharField(max_length=255, verbose_name='Игровое имя'),
        ),
        migrations.AlterField(
            model_name='ordertable',
            name='photo',
            field=models.ImageField(upload_to='order_tables/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='ordertable',
            name='real_name',
            field=models.CharField(max_length=255, verbose_name='Настоящее имя'),
        ),
        migrations.AlterField(
            model_name='ordertable',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_tables', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='main.event', verbose_name='Мероприятие'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='friends_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество друзей'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
